# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - fenix_taskgraph.signing:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - old-decision

job-defaults:
    description: Sign Fenix
    index:
        type: signing
    worker-type:
        by-variant:
            (nightly|nightly-legacy|production):
                by-level:
                    '3': signing
                    default: dep-signing
            default: dep-signing
    worker:
        signing-type:
            by-variant:
                (nightly|nightly-legacy|production):
                    by-level:
                        '3': release-signing
                        default: dep-signing
                default: dep-signing
    run-on-tasks-for: []
    treeherder:
        kind: build
        tier: 2
        platform: android-all/opt

jobs:
    performance-test:
        attributes:
            build-type: performance-test
        worker-type: dep-signing
        dependencies:
            build: 'assemble: geckoNightlyForPerformanceTest'   # comes from the old-decision task
        treeherder:
            symbol: forPerformanceTest(s)

    production:
        attributes:
            build-type: production
        dependencies:
            build: 'Build FenixProduction task'  # comes from the old-decision task
        run-on-tasks-for: [github-release]
        treeherder:
            symbol: production(s)

    nightly:
        attributes:
            build-type: nightly
            nightly: true
        dependencies:
            build: 'Build FenixNightly task' # comes from the old-decision task
        treeherder:
            symbol: nightly(s)

    nightly-legacy:
        attributes:
            build-type: nightly-legacy
            nightly: true
        dependencies:
            build: 'Build FenixNightlyLegacy task'  # comes from the old-decision task
        treeherder:
            symbol: nightly-legacy(s)
