# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.
---

jobs:
    - name: raptor
      job:
          type: decision-task
          treeherder-symbol: raptor-D
          # TODO change target method once first tasks are migrated off "old-decision"
          target-tasks-method: raptor
      when: [{hour: 1, minute: 0}]
