# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.
---

jobs:
    - name: nightly
      job:
          type: decision-task
          treeherder-symbol: Nd
          target-tasks-method: nightly
      when:
          - {hour: 6, minute: 0}
          - {hour: 18, minute: 0}
    - name: fennec-nightly
      job:
          type: decision-task
          treeherder-symbol: N-fennec
          target-tasks-method: fennec-nightly
      when: []  # Force hook only
    - name: raptor
      job:
          type: decision-task
          treeherder-symbol: raptor-D
          target-tasks-method: raptor
      when: [{hour: 1, minute: 0}]
