---
loader: taskgraph.loader.transform:loader
transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    worker-type: always-optimized
    run:
        using: index-search

jobs:
    nightly:
        description: "upstream nightly job"
        run:
            index-search:
                - gecko.v2.mozilla-central.shippable.latest.mobile.android-x86_64-opt
