  MozillaBannedPropertyAccess:
    active: true
    bannedProperties: "Sample.Banned"
  MozillaBannedMethodInvocation:
    active: true
    bannedMethods: ".*Foo\\.bannedMethodX.*, .*Foo\\.bannedMethodY.*, .*forbidden.*, .*[mMisconfigured.*"