blank_issues_enabled: false
contact_links:
  - name: We are now using Bugzilla for issue tracking!
    url: https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix
    about: Please file your ticket there, and select the corresponding component from the list. If the component is not in the list, select "General". In commit messages, please reference the ticket using "Bug 1234567 - " as prefix.
