# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - signing


jobs:
    nightly:
        attributes:
            nightly: true
        dependencies:
            signing: signing-nightly
        description: Upload APKs to Nimbledroid for performance measurement and tracking
        run:
            commands:
                - [wget, {artifact-reference: '<signing/public/build/armeabi-v7a/geckoNightly/target.apk>'}, '-O', target.apk]
                - [python, automation/taskcluster/upload_apk_nimbledroid.py, target.apk, .nimbledroid_token]
            secrets:
                - name: project/mobile/fenix/nimbledroid
                  key: api_key
                  path: .nimbledroid_token
            using: run-commands
            use-caches: false
        run-on-tasks-for: []
        treeherder:
            kind: test
            platform: android-all/opt
            symbol: nimbledroid
            tier: 2
        worker:
            docker-image: {in-tree: nimbledroid}
            max-run-time: 600
        worker-type: b-android
