# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.docker_image:transforms
    - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.task:transforms

jobs:
    base:
        symbol: I(base)
    nimbledroid:
        parent: base
        symbol: I(nimbledroid)
    ui-tests:
        parent: base
        symbol: I(ui-tests)
