# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.fetch:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    docker-image: {in-tree: base}

jobs:
    android-sdk-3859397:
        description: Android SDK
        fetch:
            type: static-url
            url: https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
            artifact-name: sdk-tools-linux.zip
            sha256: 444e22ce8ca0f67353bda4b85175ed3731cae3ffa695ca18119cbacef1c1bea0
            size: 136964098
        artifact-prefix: mobile/android-sdk
        fetch-alias: android-sdk
