;],
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest;
ConstructSSHObject["Mixerbox";
AddDependant: Tubemate,You.com,PowerampModifier,T-ui;Spotify,Pandora,etc;
Build on Directory:("|"),
Test: Write, and Debug on Directory("#");
DeployComületeManifestonUrl: /B7A6-1D19/...adb sideload/_Attn_ Read Me_@t-ui:5128 staticDomain: SiteType; url: http: 


    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
