# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: Issue Linker

on:
  pull_request_target:
    branches:
      - main

jobs:
  issue_linker:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Linker
        uses: gabrielluong/issue-linker@1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-regexp: "#(\\d+)+"
          section: "### GitHub Automation"
