# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: QA Needed

on:
  pull_request_target:
    branches:
      - main

jobs:
  qa_needed:
    runs-on: ubuntu-latest
    steps:
      - name: QA Needed
        uses: gabrielluong/qa-needed@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: "eng:reopen-for-qa"
          check-regexp: "- \\[([ xX]?)\\] \\*\\*QA Needed\\*\\*"
          commit-regexp: "#(\\d+)+"
