# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: Reopen for QA Needed

on:
  issues:
    types:
      - closed

jobs:
  reopen_qa_needed:
    runs-on: ubuntu-latest
    steps:
      - name: Reopen for QA Needed
        uses: gabrielluong/reopen-for-qa-needed@1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reopen-label: "eng:reopen-for-qa"
          qa-label: "eng:qa:needed"
